# -*- coding: utf-8 -*-

k1 = """[PROSE & IN-LINE SPATIAL & GLOBAL LOCK]: [0s-10s] A 2D anime screencap from a modern 2D TV anime episode on rain-swept rooftop (@image_env1), delinquent Kaito (@image2) violently slams Ren (@image1) into the chain fence corner. Ren, with messy black india ink hair, tattered uniform, and cracked rectangular spectacles, does not flinch; his bandaged fingers slowly adjust his glasses on his nose bridge. Kaito grips Ren's collar, screaming out in rage in English: "Look at me when I'm breaking you, you worthless trash!" Ren's pupils narrow with composure, whispering back in cold English: "I am looking, Kaito. I'm looking at someone terrified of tomorrow." Foreground rain streaks slice through frame as painted Tokyo city skyline glows in indigo background. Locked strictly to @image1, @image2, and @image_env1. Exactly two subjects, single continuous 2.5m fence, flat 2D layout layout perspective.

[ACTING & LIGHTING SCIENCE]: Modern 2D anime production still. Clean digital outline ink lines, expressive micro-acting, fluid keyframe posture. Flat shading, hard shadow lines, flat color fills, white ink reflections on hair and spectacles, modern TV anime broadcast style. Atmospheric painted lighting with deep indigo tones contrasted by harsh yellow floodlight cutlines. Uncompressed 32-bit float audio mix, clear vocal presence, metallic fence rattle. [COLOR GRADE LOCK]: Primary Triadic Separation (Midnight Indigo, Acid Amber, Crimson Blood).

[CAMERA SCIENCE & KINETIC PHYSICS]: [SUBJECT MOTION: Violent collar shove into fence followed by calm finger adjustment of spectacles and subtle lip movement] [CAMERA MOTION: Dynamic 2D camera push-in tracking, animating on twos with a hand-drawn 12fps motion cadence, staggered 12fps hand-drawn keyframe pacing, limited-rate frame-by-frame cadence, discrete cell updates, hand-drawn Obake smears, multi-plane parallax]. Traditional hand-painted anime background: digital art layers, painted wet asphalt. 9:16 vertical framing, real-time 1.0x."""

k2 = """[PROSE & IN-LINE SPATIAL & GLOBAL LOCK]: [10s-20s] Seamless cut-on-action from Dutch angle to reverse medium two-shot along rain-swept fence corner (@image_subenv1) as enforcer Daiki (@image3) steps into frame with clenched fists beside Kaito (@image2). Ren (@image1), in upright posture with rain streaming down his chin, steps forward 10cm into their space, unflinching beneath a lightning flash. Daiki snarls with jaw tension, shouting in English: "Shut his mouth before I shatter his teeth across this roof!" Ren maintains cold eye-contact, delivering words in English: "Go ahead. But every tooth you break... is another year added to your father's fraud trial." In blurred foreground, Daiki's knuckles tremble while Kaito's fingers loosen from Ren's collar. Locked to @image1, @image2, @image3, and @image_subenv1. Exactly three subjects present, single 2.5m fence perimeter, flat 2D layout.

[ACTING & LIGHTING SCIENCE]: Modern 2D anime production still. Clean digital outline ink lines, detailed facial micro-expressions. Intimidating posture. Micro-dilation of pupils, steady focus. Flat shading, hard shadow lines, flat color fills, modern TV anime broadcast style. Atmospheric hand-painted lighting wrapping around subjects in deep indigo and yellow shadow cutlines. Uncompressed 32-bit float audio mix, punchy dialogue presence, rolling thunder resonance. [COLOR GRADE LOCK]: Primary Triadic Separation (Midnight Indigo, Acid Amber, Crimson Blood).

[CAMERA SCIENCE & KINETIC PHYSICS]: [SUBJECT MOTION: Aggressive step forward into frame, subtle knuckle clench, deliberate micro-advance by protagonist] [CAMERA MOTION: Sakuga dynamic lateral tracking arc to reverse angle, animating on twos with a hand-drawn 12fps motion cadence, staggered 12fps hand-drawn keyframe pacing, limited-rate frame-by-frame cadence, discrete cell updates, hand-drawn Obake smears, multi-plane parallax]. Traditional hand-painted anime background: digital art layers, painted wet asphalt. 9:16 vertical framing, real-time 1.0x."""

k3 = """[PROSE & IN-LINE SPATIAL & GLOBAL LOCK]: [20s-30s] Cut-on-action to high-angle close-up at fence junction (@image_subenv1) as rain pours across frozen face of Kaito (@image2), whose arrogant sneer dissolves into panic. Ren (@image1), stepping closer so his shadow looms across Kaito's trembling features, tilts his chin down with an icy gaze. Kaito's hand drops from Ren's uniform, his voice trembling in desperate confusion, speaking in English: "What did you just say...? How do you know about that?!" Ren leans into Kaito's ear, whispering cold truth in English: "You beat me every day because at home... you're the one forced to kneel." Rain streaks slice through frame while wet bitumen reflects yellow halogen light in background. Locked to @image1, @image2, and @image_subenv1. Exactly two subjects in frame, single steel fence backdrop, flat 2D layout.

[ACTING & LIGHTING SCIENCE]: Modern 2D anime still. Clean digital outline lines, detailed ocular terror, mouth corner twitch. Psychological power reversal. Wet hair, white ink reflections on eyelashes, flat color fills. Flat shading, hard shadow lines, directional yellow floodlight cutlines casting sharp shadow shapes across soaked fabric against indigo background. Uncompressed 32-bit float audio, whispering vocal intimacy, atmospheric downpour. [COLOR GRADE LOCK]: Primary Triadic Separation (Midnight Indigo, Acid Amber, Crimson Blood).

[CAMERA SCIENCE & KINETIC PHYSICS]: [SUBJECT MOTION: Trembling hand release, micro-step forward, subtle head tilt and whispering jaw movement] [CAMERA MOTION: Sakuga vertical tilt-down to macro ocular framing, animating on twos with a hand-drawn 12fps motion cadence, staggered 12fps hand-drawn keyframe pacing, limited-rate frame-by-frame cadence, discrete cell updates, hand-drawn Obake smears, multi-plane parallax]. Traditional hand-painted anime background: digital art layers, painted wet asphalt. 9:16 vertical framing, real-time 1.0x."""

k4 = """[PROSE & IN-LINE SPATIAL & GLOBAL LOCK]: [30s-40s] Seamless cut-on-action to dynamic low-angle wide framing at fence corner (@image_subenv1) as Kaito (@image2) snaps, cocking his right arm back and unleashing an explosive right hook toward Ren's head. Ren (@image1), in tattered uniform, exhibits flawless composure, executing a precise duck beneath Kaito's forearm. Kaito's heavy fist strikes the galvanized chain fence, sending metallic vibrations and water droplets across frame. Kaito screams in wild desperation, speaking in English: "Shut up! Die! You're nothing! You're just a stray dog!" Ren pivots fluidly behind Kaito's shoulder, whispering in English: "A stray dog that spent three months archiving your family's offshore accounts." Rain splashes across bitumen. Locked to @image1, @image2, and @image_subenv1. Exactly two subjects, single fence, flat 2D layout.

[ACTING & LIGHTING SCIENCE]: High-velocity 2D Sakuga action animation. Clean digital outline ink lines, impact frames with line smears, dynamic hair physics, intense facial rage. Kinetic weight transfer, torque in torso. Flat shading, hard shadow lines, flat color fills. High-contrast lighting: lightning flash silhouette illuminating white impact sparks on fence mesh. Uncompressed 32-bit float audio mix, steel fence clatter, heavy vocal scream. [COLOR GRADE LOCK]: Primary Triadic Separation (Midnight Indigo, Acid Amber, Crimson Flare).

[CAMERA SCIENCE & KINETIC PHYSICS]: [SUBJECT MOTION: Full-body windup punch, rapid slipping duck, fist impacting steel fence with kinetic recoil] [CAMERA MOTION: Sakuga dynamic whip-pan tracking along punch arc settling into Dutch low-angle framing, kinetic 1-koma Sakuga cadence (24fps), hand-drawn Obake smear interpolation replacing fluid motion blur, impact frames, limited frame rate cadence, discrete keyframed intervals, multi-plane parallax]. Traditional hand-painted anime background: digital art layers, painted wet asphalt. 9:16 vertical framing, real-time 1.0x."""

k5 = """[PROSE & IN-LINE SPATIAL & GLOBAL LOCK]: [40s-50s] Cut-on-action from fence impact to profile tracking across rooftop (@image_env1) as Ren (@image1) exploits Kaito's (@image2) forward momentum. Ren drives his bandaged right palm in a strike into Kaito's solar plexus, followed by a low sweeping kick. Kaito's eyes bulge in shock as heavy impact lifts his boots off the floor before slamming his back into a rain puddle on the asphalt with a water explosion. Ren stands over him, speaking in calm English: "Three years of my blood. Did you really think I was just crying in the corner?" Kaito clutches his chest, coughing water and gasping in English: "Gah... you... you psycho..." Puddle waves ripple outward while rain pounds against Kaito's jacket. Locked to @image1, @image2, and @image_env1. Exactly two active subjects, single wet floor, flat 2D layout.

[ACTING & LIGHTING SCIENCE]: Peak Sakuga kinetic impact animation. Keyframe weight transfer, line smears on strike vector, water plume dynamics. Visceral physical exhaustion versus towering psychological supremacy. Sharp facial micro-expressions, coughing diaphragm spasm, unwavering gaze. Flat shading, hard shadow lines, flat color fills, constant line-weight ink strokes. Dynamic yellow floodlight casting sharp diagonal shadow shapes across painted wet floor. Uncompressed 32-bit float audio mix, heavy chest thud, splash. [COLOR GRADE LOCK]: Primary Triadic Separation (Midnight Indigo, Acid Amber, Crimson Blood).

[CAMERA SCIENCE & KINETIC PHYSICS]: [SUBJECT MOTION: Rapid forward palm strike, sweeping low leg rotation, full-body puddle slam impact] [CAMERA MOTION: Sakuga dynamic rapid push-in tracking with full 1-koma impact freeze frame at strike contact, kinetic 1-koma Sakuga cadence (24fps), hand-drawn Obake smear interpolation replacing fluid motion blur, impact frames, limited frame rate cadence, discrete keyframed intervals, multi-plane parallax]. Traditional hand-painted anime background: digital art layers, painted wet asphalt. 9:16 vertical framing, real-time 1.0x."""

k6 = """[PROSE & IN-LINE SPATIAL & GLOBAL LOCK]: [50s-60s] Seamless cut-on-action to reverse high-angle toward industrial doorway (@image_env2) looking past Ren's (@image1) shoulders toward defeated Kaito (@image2) shivering on soaked rooftop. In background near the door, enforcer Daiki (@image3) stares, dropping his umbrella (@image_prop1) into a puddle before fleeing through the doorway. Ren tilts his chin downward, rain running off his cracked spectacles, speaking in English: "I wasn't crying. I was taking inventory." Daiki's voice echoes in terror, shouting in English: "Kaito... he's lost his mind... I'm out of here!" The umbrella floats in puddle as Kaito curls on wet bitumen. Locked strictly to @image1, @image2, @image3, @image_prop1, and @image_env2. Exactly three subjects, single steel doorframe, flat 2D layout.

[ACTING & LIGHTING SCIENCE]: Modern 2D anime production still. Clean digital outline ink lines, crisp silhouettes, rhythmic breathing of victor, shivering tremors of defeated. Paralyzed cowardice. Expressive pupil dilation, wet hair clinging to cheeks. Anime poster color painted lighting: yellow floodlight cutting a path across falling rain, framing Ren in yellow rim cutlines while deep indigo shadows swallow fleeing enforcer. Flat shading, hard shadow lines. Uncompressed 32-bit float audio mix, footsteps fleeing down metal stairs, puddle splash. [COLOR GRADE LOCK]: Primary Triadic Separation (Midnight Indigo, Acid Amber, Crimson Blood).

[CAMERA SCIENCE & KINETIC PHYSICS]: [SUBJECT MOTION: Victorious upright stillness, defeated shivering crawl, umbrella drop and panicked doorway sprint] [CAMERA MOTION: Sakuga high-angle slow crane track settling into low-angle two-shot framing Ren and dropped umbrella, animating on twos with a hand-drawn 12fps motion cadence, staggered 12fps hand-drawn keyframe pacing, limited-rate frame-by-frame cadence, discrete cell updates, hand-drawn Obake smears, multi-plane parallax]. Traditional hand-painted anime background: digital art layers, painted wet asphalt. 9:16 vertical aspect ratio. Real-time 1.0x."""

k7 = """[PROSE & IN-LINE SPATIAL & GLOBAL LOCK]: [60s-70s] Cut-on-action to intimate low-angle Dutch framing at fence corner (@image_subenv1) as Ren (@image1) crouches down in a rain puddle, bringing his face level with shivering Kaito (@image2). Ren's hand retrieves a black USB flash drive (@image_prop1) from his jacket pocket, holding the metallic drive before Kaito's wide, terror-filled eyes. Ren speaks in an icy whisper in English: "Tomorrow morning, your dynasty burns. Tonight... you apologize on your knees." Kaito sobs softly with trembling lips, stammering in English: "P-Please... Ren..." At timestamp 09.0s, Ren slowly turns his cold gaze straight into the camera frame with an enigmatic smirk as lightning illuminates the frame before a smash cut to black at 10.0s. Locked to @image1, @image2, @image_prop1, and @image_subenv1. Exactly two subjects, single USB flash drive in hand, flat 2D layout.

[ACTING & LIGHTING SCIENCE]: Master-tier 2D Sakuga dramatic animation. Clean digital outline ink lines, hyper-expressive micro-facial acting: trembling lower lip of defeated bully, razor-sharp psychopathic calm of protagonist, subtle lifting of smirk corner. White ink reflections on hair, raindrops on cheekbones, constant line-weight ink strokes. Flat shading, hard shadow lines, flat color fills. Dramatic lighting: harsh yellow rim cutlines highlighting metallic edges of USB drive, culminating in pure white lightning strobe silhouette. Uncompressed 32-bit float audio mastering, intimate vocal proximity, soft sobbing breath, crack of thunderclap. [COLOR GRADE LOCK]: Primary Triadic Separation (Midnight Indigo, Acid Amber, Crimson Blood).

[CAMERA SCIENCE & KINETIC PHYSICS]: [SUBJECT MOTION: Controlled one-knee crouch, smooth hand presentation of USB drive, slow head turn toward camera] [CAMERA MOTION: Sakuga slow intimate push-in settling on macro framing of Ren's eyes and glowing USB drive, ending in instantaneous smash cut to black, animating on twos with a hand-drawn 12fps motion cadence, staggered 12fps hand-drawn keyframe pacing, limited-rate frame-by-frame cadence, discrete cell updates, hand-drawn Obake smears, multi-plane parallax]. Traditional hand-painted anime background: digital art layers, painted wet asphalt. 9:16 vertical framing, real-time 1.0x."""

all_k = [k1, k2, k3, k4, k5, k6, k7]
for idx, p in enumerate(all_k, 1):
    print(f"Klip {idx}: {len(p)} characters")
    assert 1900 <= len(p) <= 1950, f"Klip {idx} failed with {len(p)} chars"

print("ALL 7 CADENCE-LOCKED MODERN ANIME PROMPTS SUCCESSFULLY VERIFIED (1,900 - 1,950 CHARACTERS)!")
